--- 
- name: This sets up an apache webserver
   sudo: yes
   hosts: 172.31.36.123
   tasks: 
   - name: Uninstall apache packages
     apt: name=apache2 update_cache=yes state=absent
   - name: Install apache packages
     apt: name=apache2 update_cache=yes state=latest
   - name: Ensure apache2 is installed
     apt: name=apache2 state=present
